### ISSUE TITLE
Proper way to use SSML with SpeakSentence?

### ISSUE THREAD

**Issue by alexthekid07** [Bandwidth/csharp-sdk#41]
Trying to do some basic SSML stuff with text-to-speech and I'm encountering issues.

```
Dim speakSentenceCommand As New SpeakSentence With {
	.Gender = "female",
	.Locale = "en_US",
	.Voice = "julie",
	.Sentence = "Hello <p> Test"
}
Return New Response(speakSentenceCommand).ToBXML()
```

This results in nothing being spoken at all, and a callback barking about invalid BXML.
If I remove the `<p>`, it works fine. The same happens for other SSML like `<say-as>`.
Is there a different way I should be passing SSML through the SDK?

**Comment by hamermike** [comment]
We'll take a look at this and get back to you with additional information.

**Comment by ajrice6713** [comment]
Hey @alexthekid07,

Digging into this. at first glance your `<p>` is missing the close tag - so changing it to `<p/>` should result in a successful call. 

Can you provide examples for how you are using the `<say-as>` tag? 

The callbacks should include detailed errors in the `errorMessage` object like such: 
```

**Comment by alexthekid07** [comment]
I think I may have misinterpreted how <p> works based on the documentation. I was under the impression it worked like <break> and didn't need a separate closing tag. Thanks for the clarity.

**Comment by ajrice6713** [comment]
@alexthekid07 let me know if there is any action we need to take on this - i ran some tests locally and the SDK seems to be generating the `<Sentence>` elements fine (no encoding issues which was my first thought). 

Additionally - if you have any questions or issues surrounding our documentation - that is open source as well and you can always open issues against that repo

https://github.com/Bandwidth/api-docs
