### ISSUE TITLE
Bandwidth.Standard.Voice.Models.CallCallback does not define parameters for machineDetectionComplete event

### ISSUE THREAD

**Issue by alexthekid07** [Bandwidth/csharp-sdk#42]
`Bandwidth.Standard.Voice.Models.CallCallback` does not seem to have the `machineDetectionResult` or it's children.
https://github.com/Bandwidth/csharp-sdk/blob/cbb3c9f48c2aec10fdc985ddb4edc5283a6ca5c0/Bandwidth.Standard/Voice/Models/CallCallback.cs

This prevents properly deserializing the `machineDetectionComplete` webhooks into a `CallCallback` object.
As a workaround I'm parsing the webhook JSON manually.

**Comment by ajrice6713** [comment]
Hey @alexthekid07 

Thanks for raising this issue - Ill get a fix going and close this issue once its merged in!

**Comment by ajrice6713** [comment]
Hey @alexthekid07 

v8.2.0 with this fix just released and is available.
