### ISSUE TITLE
Phone dialer sample (C# desktop or web based)

### ISSUE THREAD

**Issue by sensboston** [Bandwidth/csharp-sdk#63]
Do you guys have an example of desktop phone dialer (with ability to make a phone call), or might be a web-based phone dialer (can be embedded to the WebView2 control)?

We just want to implement following scenario for our business needs: 
- start a _silent_ call (no dial tones, dial rings etc.)
- monitor call status (dialing, connected etc.)
- if voicemail or answering machine detected, end this call and set a call status or return a code
- if human detected, continue voice call
- will be good to have ability to control call programmatically (hung up, transfer, put on hold etc.)

Pretty simple and useful scenario, isn't it? But we still can't find a proper service for that simple scenario 😢 - it looks like **nobody** implemented that.

**Comment by ajrice6713** [comment]
Hey @sensboston! thanks for reaching out. 

Sounds like this is more of a WebRTC based use case in conjunction with the voice API product (specifically the soft phone functionality) - I don't know if we have samples of that with a C# backend, i think most of those are written with a nodeJs backend since our [browser sdk](https://github.com/bandwidth/webrtc-browser) is javascript.

All of our more complex WebRTC sample applications can be found [here](https://github.com/orgs/Bandwidth-Samples/repositories?language=&q=webrtc&sort=&type=all), and it looks like we have python and java examples - I'd have to get some work on our backlog to see about getting a C# example posted. 

We do have examples of the C# client and programatic voice api [here](https://github.com/orgs/Bandwidth-Samples/repositories?q=voice+csharp&type=all&language=&sort=) highlighting gathering user input and recording calls - but I can get some work on our backlog to get a more fully fledged sample using the voice api - however only using the voice api product without WebRTC wont allow you to build your own soft phone/web dialer application. 

Are you already a contracted BW customer? It might be useful for us to get an idea of your use case and look at what kind of examples would be the most helpful.

**Comment by sensboston** [comment]
Thanks for quick reply @ajrice6713

Nope, I'm not a BW customer: I don't wanna waste your guys time for processing registration request until I get a proof of required functionality (btw, we're already tried Dialpad, Twilio etc. and spent lot of time: result - no luck at all 😞 )

It's a pity that you don't have production ready phone dialer/"soft phone" with useful API (even web-base). 

I'm really curious: are we asking for some pretty unusual and specific (I mean our preferred call scenario I mentioned in OP)? I still thinking, it's a pretty useful, to save employees time and ears, and shouldn't be hard for you guys to implement 'cause you already have all required "pieces of puzzle".

**Comment by ajrice6713** [comment]
Sorry to hear you've had no luck with the others - As it stands today, Bandwidth doesn't provide an out of the box soft-phone solution that would allow you to configure call flows - We offer the APIs to allow you to build something to your liking, but supporting a distributed application isn't something thats currently on our roadmap. 

The features you listed above are all possible with our current APIs - it would just require dev work on your side to implement with our [Voice](https://dev.bandwidth.com/docs/voice/) and [WebRTC](https://dev.bandwidth.com/docs/webrtc/) APIs. We take more of a platform stance and offer customers the tools to build their own custom solutions leveraging our network. 

This [sample application](https://github.com/Bandwidth-Samples/webrtc-phone-advanced-react) has examples of a couple of the features you are looking for (dial from browser, monitor call status (should show in console logs), call could be started silently), and [Answering Machine Detection](https://dev.bandwidth.com/docs/voice/guides/machineDetection) would be easy to implement in the outbound [call creation API request](https://github.com/Bandwidth-Samples/webrtc-phone-advanced-react/blob/12df3a363548d74f69502b1f8857a7be914de24f/src/server.ts#L362). 

You aren't asking for anything unusual - this is a pretty standard use case for consumers of our WebRTC product - its just that the overwhelming majority of them are working in Javascript and NodeJS/TypeScript - so most of our examples are written in that. 

Our C# SDK does have all of the necessary methods to build a server to handle this - and we do have code examples of each method in the specific API references ([Voice](https://dev.bandwidth.com/apis/voice/) and [WebRTC](https://dev.bandwidth.com/apis/webrtc/)) (You should see a language switcher on the right hand side with C# code examples)- just unfortunately not a fully fledged example in C# at this time.

**Comment by sensboston** [comment]
OK, thanks a lot! I'll try to get a trial registration; by the way, you haven't provide a prices so I should ask our CEO to get a price quota first. But your last post and sample app are looking promising.

**Comment by ajrice6713** [comment]
Sounds good! I would recommend reaching out via the forms on [our website](https://www.bandwidth.com) or by calling our offices at `+1 844 815 3639` and telling them you're interested in speaking to someone about the Voice and Video/WebRTC APIs. 

Pricing is a little outside of my wheelhouse - but we do publish our Voice API pricing [here](https://www.bandwidth.com/pricing/) - although im unsure of what additional costs there would be to incorporate WebRTC calling, if any. 

Ill close the issue out for the time being - and if you decide to go forward with a trial and need further technical assistance, please feel free to reach out on GitHub or ask to be connected with someone in Sales Engineering or Developer Experience (my team).

**Comment by sensboston** [comment]
Sure, of course! I'm so sorry I opened that issue with a "bug" label, but I always prefer to discuss technical stuff with the devs, not a tech support persons (and you know "why", I think so 😉)

P.S. @ajrice6713, the only thing I can suggest to you (and "yes", I do know you've never asked for any "free advises" 😉): could you please bring an idea about production grade standalone app (probably, web-based, and using some Chrome-based controls (read - WebView2) available not for the web only) to your management? Your competitors already has some kind of solutions but with lack of API and specific features. This project is relatively easy to implement (for the experienced devs team: btw, I know, some things aren't really easy like an echo-cancelling etc.) but the out of box, easy to use solution will add your business more customers and prospects. Kinda "win-win situation" 😉

**Comment by ajrice6713** [comment]
Hey @sensboston - no worries, i totally understand! Thats the reason our repos are public - we are happy to discuss stuff like this. 

Adding our team's product owner @dyeam-bw for visibility to that request - he works with management to help guide product decisions based on customer feedback, I'm sure he'd be happy to dig deeper into this.
